export const ABOUT = "/about-us"
export const COMPANY_FORMATION = "services/company-formation"
export const BANKING_LICENSE = "services/banking-license"
export const GAMING_LICENSE = "services/gaming-license"
export const RESIDENCE_PASSPORT = "services/residence-passport"
export const WESTERN_SAHARA = "regions/western-sahara"
export const ST_LUCIA = "regions/st-lucia"
export const ST_VINCENT = "regions/st-vincent"
export const COMOROS = "regions/comoros"
export const ASSEST_PROTECTION = "/asset-protection"
export const CONTACT_US = "/contact-us"

